#!/bin/fish

## CONFIGURATION

# Set music dir location
set musicdir $HOME/media/music

## FUCNTIONS

# This function extracts the current playing album location
function path
	mpc -f '%file%' | head -n 1 | string match -r '.*/'
end

# This function displays the cover
function spawncover
	n30f -x 1735 -y 62 $musicdir/{$path}cover_popup.png &
end


## EXECUTE

# Check if popup is open
if test -z (pgrep -f 'n30f -x 1725')
	set path (path)

	n30f -x 1725 -y 42 $HOME/.lemonbar/popups/music/bg.png &
	sleep 0.01

	spawncover

	# Keep checking for new covers whilst open
	mpc idleloop player | while read
		set pathnew (path)

		if test $path != $pathnew
			if test -f $musicdir/$path/cover_popup.png
				set path (path)
				set pathnew $path

				spawncover
				pkill -o -f 'n30f -x 1735'
			else
				set path (path)
				set pathnew $path

				spawncover
			end
		end
	end
else
	pkill -f 'n30f -x 1735'
	pkill -f 'n30f -x 1725'
	pkill -f -n 'mpc idleloop player'
end
