#!/bin/fish

# Set media dir location
set mediadir $HOME/media/videos

# Set video player command
set playercommand mpv --fullscreen --no-pause

# Set colors
set foreground normal
set bright yellow --bold
set dark black --bold

# Run the following commands before starting mpv
# (to pause mpd for example)
function userfunction
	# Pause mpc
	mpc -q pause

	# Close clock popup
	if test (pgrep -f 'n30f -d -x 870' | head -n 1)
		pkill -n -f 'n30f -d -x 870'
		pkill -f 'n30f -d -x 85'
		pkill -f 'lemonbar -g 168x20'
	end

	# Close album popup
	if test (pgrep -f 'n30f -d -x 1725' | head -n 1)
		pkill -f "n30f -d -x 1735"
		pkill -f "n30f -d -x 1725"
		pkill -f -n "mpc idleloop player"
	end
end
