#!/bin/fish
#
# symlink - links dotfiles
# onodera, https://github.com/onodera-punpun

## CONFIGURATION

# Dotfiles location
set d $HOME/dotfiles

# ln options
set o -s -f -v -n


## EXECUTE

sudo echo -n ''
if test $status -ge 1
	exit 1
end

# Link dotfiles
ln $o $d/fonts                 $HOME/.fonts
rm -r                          $HOME/.config/fish
ln $o $d/fish                  $HOME/.config
ln $o $d/fish/config           $HOME/.config/fish/config.fish
ln $o $d/irssi                 $HOME/.irssi
ln $o $d/keepers               $HOME/.keepers
ln $o $d/lemonbar              $HOME/.lemonbar
ln $o $d/mozilla               $HOME/.mozilla
ln $o $d/mpd                   $HOME/.mpd
ln $o $d/mpd/config            $HOME/.mpdconf
ln $o $d/mpdscribble           $HOME/.mpdscribble
ln $o $d/mpv                   $HOME/.mpv
ln $o $d/ncmpcpp               $HOME/.ncmpcpp
ln $o $d/neet                  $HOME/.neet
ln $o $d/openbox               $HOME/.config/openbox
ln $o $d/openbox/theme         $HOME/.themes/minato/openbox-3
ln $o $d/prtpatch              $HOME/.prtpatch
ln $o $d/rootshuf              $HOME/.rootshuf
sudo ln $o $d/ssh              $HOME/.ssh
ln $o $d/transmission          $HOME/.config/transmission-daemon
ln $o $d/vim                   $HOME/.vim
ln $o $d/vim/config            $HOME/.vimrc
ln $o $d/xdg/user-dirs.dirs    $HOME/.config/user-dirs.dirs
ln $o $d/x11/xinit             $HOME/.xinitrc
ln $o $d/x11/xresources        $HOME/.Xresources

# Copy root dotfiles
sudo cp -r $d/vim              /root/.vim
sudo cp -r $d/vim/config       /root/.vimrc

# Copy etc files
sudo cp -r $d/alsa/config      /etc/asound.conf
sudo cp -r $d/fstab            /etc/fstab
sudo cp -r $d/pkgmk/config     /etc/pkgmk.conf
sudo cp -r $d/ports            /etc/ports
sudo cp -r $d/prt-utils/config /etc/prt.conf
sudo cp -r $d/prt-get/config   /etc/prt-get.conf
sudo cp -r $d/rc/config        /etc/rc.conf
sudo cp -r $d/rc/scripts/*     /etc/rc.d
sudo cp -r $d/sshd/config      /etc/ssh/sshd_config
sudo cp -r $d/x11/config       /etc/X11/xorg.conf
