#!/bin/fish

## EXECUTE

# Spawn initial icon (else it will only spawn after inotifywait says something)
set count (wc -l $HOME/.notify/log | cut -d ' ' -f 1)
n30f -x 1886 -y 21 -c 'echo -n >$HOME/.notify/log' $HOME/.lemonbar/assets/$count.png &

inotifywait -q -m -e CLOSE_WRITE $HOME/.notify/log | while read
	set count (wc -l $HOME/.notify/log | cut -d ' ' -f 1)

	# Spawn new alert
	n30f -x 1886 -y 21 -c 'echo -n >$HOME/.notify/log' $HOME/.lemonbar/assets/$count.png &

	# Kill old alert
	pkill -o -f 'n30f -x 1886'
end
