#!/bin/fish

# Start window bar
begin
	set -l -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1 -freetype-kochismall-medium-r-normal--9-90-75-75-p-77-iso10646-1 -freetype-baekmuksmall-medium-r-normal--9-90-75-75-p-38-iso10646-1
	set -l -x fg FFFFFF
	set -l -x bg 37BF8D

	fish $HOME/.lemonbar/window | lemonbar -g 220x29+0+0 -f $font[1] -f $font[2] -f $font[3] -B \#$bg -F \#$fg &
end

# Start desktop bar
begin
	set -l -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1
	set -l -x fg FFFFFF
	set -l -x bg 5394C9 72A7D3

	fish $HOME/.lemonbar/desktop | lemonbar -g 210x29+220+0 -f $font -B \#$bg[1] -F \#$fg | dash &
end

# Start clock bar
begin
	set -l -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1
	set -l -x fg CCCCCC
	set -l -x bg 445967

	fish $HOME/.lemonbar/clock | lemonbar -g 1060x29+430+0 -f $font -B \#$bg -F \#$fg | dash &
end

# Start music bar
begin
	set -l -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1 -freetype-kochismall-medium-r-normal--9-90-75-75-p-77-iso10646-1 -freetype-baekmuksmall-medium-r-normal--9-90-75-75-p-38-iso10646-1
	set -l -x fg CCCCCC
	set -l -x bg 445967 3C4F5B

	fish $HOME/.lemonbar/music | lemonbar -g 570x29+1321+0 -f $font[1] -f $font[2] -f $font[3] -B \#$bg[1] -F \#$fg | dash &
end

# Start todo bar
begin
	set -l -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1
	set -l -x fg FFFFFF
	set -l -x bg 5394C9

	echo "%{c}%{A:fish $HOME/.lemonbar/popups/todo/launcher:}  ­  %{A}" | lemonbar -p -g 29x29+1891+0 -f $font -B \#$bg -F \#$fg | dash &
	fish $HOME/.lemonbar/todo
end
