#!/bin/fish

## EXECUTE

xdesktop -s | \
while read desktop
	switch $desktop
		case 0
			echo "%{c}%{B#FF$fg}%{F#FF$bg} www %{B#00$bg}%{F#FF$fg}  irc   src  "
		case 1
			echo "%{c} www  %{B#FF$fg}%{F#FF$bg} irc %{B#00$bg}%{F#FF$fg}  src  "
		case 2
			echo "%{c} www   irc  %{B#FF$fg}%{F#FF$bg} src %{B#00$bg}%{F#FF$fg} "
	end
end
