#!/bin/fish

## EXECUTE

xdesktop -s | \
while read desktop
	switch $desktop
		case 0
			echo "%{A4:fish $HOME/.wmutils/desktop -:}%{A5:fish $HOME/.wmutils/desktop +:}%{B#$bg2}  ¼   www    %{A:fish $HOME/.wmutils/desktop 2:}%{B#$bg1}  ½   irc    %{A}%{A:fish $HOME/.wmutils/desktop 3:}%{B#$bg1}  ¾   src    %{A}%{A}%{A}"
		case 1
			echo "%{A4:fish $HOME/.wmutils/desktop -:}%{A5:fish $HOME/.wmutils/desktop +:}%{A:fish $HOME/.wmutils/desktop 1:}%{B#$bg1}  ¼   www    %{A}%{B#$bg2}  ½   irc    %{A:fish $HOME/.wmutils/desktop 3:}%{B#$bg1}  ¾   src    %{A}%{A}%{A}"
		case 2
			echo "%{A4:fish $HOME/.wmutils/desktop -:}%{A5:fish $HOME/.wmutils/desktop +:}%{A:fish $HOME/.wmutils/desktop 1:}%{B#$bg1}  ¼   www    %{A}%{A:fish $HOME/.wmutils/desktop 2:}%{B#$bg1}  ½   irc    %{A}%{B#$bg2}  ¾   src    %{A}%{A}"
	end
end
