#!/bin/fish

## EXECUTE

mpc idleloop player | \
while read
	set music (mpc current | cut -d \n -f 1)
	echo "%{r}%{A4:mpc -q prev:}%{A5:mpc -q next:}%{A:fish $HOME/.lemonbar/popups/cover &:}%{B#$bg2}  »   $music   %{A}%{B#$bg1}%{A}%{A}%{A}%{A}"
end
