#!/bin/fish

## CONFIGURATION

# Set music dir location
set musicdir $HOME/media/music

# Set geometry
set geometry 1728 933

## FUCNTIONS

# This function extracts the current playing album location
function path
	mpc -f \%file\% | cut -d \n -f 1 | rev | cut -d / -f 2- | rev
end

# This function displays the cover
function cover
	n30f -x $albumgeometry[1] -y $albumgeometry[2] $musicdir/$path/cover_popup.png &
end


## EXECUTE

set albumgeometry (math $geometry[1] + 10) (math $geometry[2] + 10)

# Exit if open
if test (pgrep -f "n30f -x $geometry[1]" | head -n 1)
	pkill -f "n30f -x $geometry[1]"
	pkill -f "n30f -x $albumgeometry[1]"
	pkill -f -n "mpc idleloop player"
	exit
end

set path (path)
n30f -x $geometry[1] -y $geometry[2] $HOME/.lemonbar/popups/cover/cover_bg.png &
cover

mpc idleloop player | \
while read
	set pathnew (path)

	if test $path != $pathnew
		if test -f $musicdir/$path/cover_popup.png
			set path (path)
			set pathnew $path

			cover
			pkill -o -f "n30f -x $albumgeometry[1]"
		else
			set path (path)
			set pathnew $path

			cover
		end
	end
end
