#!/bin/fish

## CONFIGURATION

# Set music dir location
set musicdir $HOME/media/music

## FUCNTIONS

# This function extracts the current playing album location
function path
	mpc -f \%file\% | cut -d \n -f 1 | rev | cut -d / -f 2- | rev
end

# This function displays the cover
function cover
	n30f -d -x 1735 -y 975 $musicdir/$path/cover_popup.png &
end


## EXECUTE

# Exit if open
if test (pgrep -f "n30f -d -x 1725")
	pkill -f "n30f -d -x 1735"
	pkill -f "n30f -d -x 1725"
	pkill -f -o "lemonbar/popop/cover"
	pkill -f -n "mpc idleloop player"
	exit
end

set path (path)
n30f -d -x 1725 -y 965 $HOME/.lemonbar/popups/cover_bg.png &
cover

mpc idleloop player | \
while read
	set pathnew (path)

	if test $path != $pathnew
		set path (path)
		set pathnew $path

		pkill -f "n30f -d -x 1735"

		cover
	end
end
