#!/bin/fish

## EXECUTE

# Check if clock popup is open
if test -z (pgrep -f 'n30f -x 871')
	set -x font -artwiz-cure-medium-r-normal--11-110-75-75-p-90-iso8859-1
	set -x fg 021B21
	set -x bg EEEEEE

	n30f -x 871 -y 29 $HOME/.lemonbar/popups/clock/bg.png &

	raingraph /tmp/raingraph.png
	n30f -x 857 -y 29 /tmp/raingraph.png &
	fish $HOME/.lemonbar/popups/clock/celsius | lemonbar -g 168x20+872+118 -p -d -f $font -B \#00$bg -F \#$fg &
	fish $HOME/.lemonbar/popups/clock/moon | lemonbar -g 168x20+872+42 -p -d -f $font -B \#00$bg -F \#$fg &
else
	pkill -n -f 'n30f -x 871'
	pkill -f 'n30f -x 857'
	pkill -f 'lemonbar -g 168x20'
end
