#!/bin/fish

## EXECUTE

set phase (math '((('(date --date='00:00' +%s)' - 1386030360) % 2551443) / 86400)')

switch $phase
	case in 0 1 29
		echo '  The moon looks like ² tonight.'
	case in 2 3 4 5
		echo '  The moon looks like ³ tonight.'
	case in 6 7 8 9
		echo '  The moon looks like ´ tonight.'
	case in 10 11 12 13
		echo '  The moon looks like µ tonight.'
	case in 14 15 16
		echo '  The moon looks like ¶ tonight.'
	case in 17 18 19 20
		echo '  The moon looks like · tonight.'
	case in 21 22 23 24
		echo '  The moon looks like ¸ tonight.'
	case in 25 26 27 28
		echo '  The moon looks like ¹ tonight.'
end
