#!/bin/fish

# Set media dir location
set mediadir $HOME/media/videos

# Set video player command
set playercommand mpv --fullscreen --no-pause

# Set colors
set foreground normal
set bright yellow --bold
set dark black --bold

# Run the following commands before starting mpv
# (to pause mpd for example)
function userfunction
	# Pause mpc
	mpc -q pause

	# Close clock popup
	if test (pgrep -f 'n30f -d -x 871')
		pkill -n -f 'n30f -x 871'
		pkill -f 'n30f -x 857'
		pkill -f 'lemonbar -g 168x20'
	end

	# Close music popup
	if test (pgrep -f 'n30f -x 1587')
		pkill -f 'n30f -x 1753'
		pkill -f 'lemonbar -g 140x20'
		pkill -f 'n30f -x 1587'
		pkill -f -n 'mpc idleloop player'
	end

	# Close todo popuo
	pkill -f "micro $HOME/.todo"
end
